@apiURL={{$dotenv API_URL}}
@authToken={{$dotenv TEMP_TOKEN}}

### Hämta alla produkter (Require Auth)
GET {{apiURL}}products
Authorization: Bearer {{authToken}}

### Hämta en specifik produkt (Require Auth)
GET {{apiURL}}products/{sku}
Authorization: {{authToken}}

### Lägg till en ny produkt (Require Auth)
POST {{apiURL}}products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "sku": "785-GFI",
    "name": "IPA",
    "price": 62.99,
    "description": "En kraftig och humlearomatisk IPA.",
    "image": "path-to-image"
}

### Uppdatera en produkt (Require Auth)
PUT {{apiURL}}products/{id}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Pale Ale Special Edition",
    "price": 69.99
}

### Ta bort en produkt (Require Auth)
DELETE {{apiURL}}products/{id}
Authorization: Bearer {{authToken}}
